### ISSUE TITLE
postgres authed failed

### ISSUE THREAD

**Issue by lidaling** [TouK/nussknacker-quickstart#87]
I use helm repo install the nussknacker ,the nussknacker node start failed with error below
```
Unable to obtain connection from database (jdbc:postgresql://my-nussknacker-postgresql/) for user 'postgres': FATAL: password authentication failed for user "postgres"
```
env: 
k3d rancher with 3 agent

**Comment by gadomsky** [comment]
Hi @lidaling, thank you for reporting the issue.
We had a bug in providing secret name with password to Bitnami's postgres helmchart (Bitnami has changed configuration recently).
We updated both [nussknacker-helm](https://github.com/TouK/nussknacker-helm/pull/62) repo and [this repo](https://github.com/TouK/nussknacker-quickstart/pull/88).

Please try again, and if anything still doesn't work (which it shouldn't) - feel free to let us know.

Before running `helm install` again, please bear in mind, to delete all `persistent volumes` and `persitent volume claims` related to postgres, so the database can initialize again with correct password.

**Comment by lidaling** [comment]
> 

OK ,I will try and give the feedback
